**PyTorch Fundamentals**

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0


**Introduction to Tensors**

\nPyTorch tensors create using torch.tensors()

In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX[0]

tensor([7, 8])

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`


In [15]:
#Create a random tensors of size (3, 4)
random_tennsor = torch.rand(2, 3, 4,5)
random_tennsor

tensor([[[[0.4112, 0.7715, 0.0972, 0.8777, 0.2880],
          [0.4203, 0.1223, 0.6974, 0.3120, 0.8321],
          [0.9147, 0.5671, 0.5803, 0.0497, 0.4103],
          [0.8015, 0.1706, 0.0023, 0.1637, 0.3986]],

         [[0.3232, 0.4319, 0.5308, 0.5442, 0.0889],
          [0.5580, 0.6333, 0.0318, 0.0391, 0.0280],
          [0.9142, 0.7341, 0.4727, 0.9635, 0.6262],
          [0.4456, 0.1113, 0.5824, 0.1238, 0.7780]],

         [[0.8989, 0.2556, 0.5863, 0.8588, 0.2354],
          [0.4812, 0.7707, 0.8240, 0.6817, 0.4653],
          [0.0819, 0.4675, 0.4615, 0.5146, 0.3268],
          [0.1937, 0.6763, 0.3446, 0.8430, 0.1152]]],


        [[[0.0217, 0.9470, 0.2199, 0.3395, 0.7805],
          [0.5471, 0.7832, 0.5330, 0.5587, 0.8459],
          [0.8183, 0.4038, 0.2516, 0.4222, 0.8027],
          [0.7412, 0.2754, 0.6085, 0.9746, 0.7633]],

         [[0.0117, 0.6924, 0.1477, 0.7264, 0.9540],
          [0.5758, 0.4095, 0.2279, 0.1641, 0.0755],
          [0.5932, 0.1068, 0.8126, 0.7132, 0.4122],
  

In [16]:
random_tennsor.ndim
random_tennsor.shape

torch.Size([2, 3, 4, 5])

In [17]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zero and Ones

In [18]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype
random_tennsor.dtype

torch.float32

### Creating a rang of tensors and tensors-like

In [21]:
# Use torch.range()
torch.arange(0, 10)
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
# Creating tesors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatype

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [23]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,          # what datatype is the tensor (e.g. float32 or float16)
                               device=None,         # What device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [24]:
float_32_tensor.dtype

torch.float32

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [26]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [27]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting information from tensors
1. Tensor not  right datatype      - to do get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape         - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor from a tensor, can use tensor.device 

In [28]:
# Create a tensor 
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6016, 0.3721, 0.4829, 0.0815],
        [0.4467, 0.2550, 0.6559, 0.1124],
        [0.7482, 0.0660, 0.4196, 0.4555]])

In [29]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [30]:
# Find out details about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.6016, 0.3721, 0.4829, 0.0815],
        [0.4467, 0.2550, 0.6559, 0.1124],
        [0.7482, 0.0660, 0.4196, 0.4555]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Add
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [31]:
# Create a tensor 
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [32]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [33]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [34]:
# Try out Pytorch built-in function
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication

Two main ways of performing multiplication in neural network and deep learning:
1. Element-wise multiplication
2. Matrix multiplciation (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **Inner deimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimesions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [43]:
torch.matmul(torch.rand(2, 3), torch.rand(3,2))

tensor([[1.0543, 1.6386],
        [1.1302, 1.4476]])

In [35]:
# Element wise multiplication 
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [36]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [37]:
tensor

tensor([1, 2, 3])

In [38]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [41]:
tensor @ tensor

tensor(14)

In [39]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

print(value)
print(len(tensor))

tensor(14)
3
CPU times: total: 15.6 ms
Wall time: 6.36 ms


In [40]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 986 μs


tensor(14)

### One of the most errors in deep learning: shape errors

In [44]:
# shapes fro matrix multiplication 
tensor_A = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])

tensor_B = torch.tensor([
    [7, 10],
    [8, 11],
    [9, 12]
])

# torch.mm is the same as torch.matmul (It's an alias)
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [53]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using **transpose**
* A **transpose** switches the axes or dimensions of a given tensor

In [54]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [55]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [59]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shape: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f'New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}')
print(f"Multiplication: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output: \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shape: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplication: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [61]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [64]:
#Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [63]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [67]:
# Find the mean - note: torch.mean() function requires of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [68]:
# Find the sum 
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Find the position of Max and Min

In [71]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [70]:
x.argmin()

tensor(0)

In [72]:
x.argmax()

tensor(9)

In [73]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing, and unsqueesing tensors
* Reshaping -- reshapes an input tensor to a defined shape
* View -- Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking -- combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze -- removes all 1 dimensions from a tensor
* Unsqueeze -- add 1 dimension to a target tensor
* Permute -- Return a view of the input with dimensions permuted (swapped) in certain way

In [88]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [89]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [90]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [91]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [92]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [97]:
# torch.squeeze() -- removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f'Previous shape: {x_reshaped.shape}')

# Remove extra dimemsions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f'\nNew shape: {x_squeezed.shape}')

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

New shape: torch.Size([9])


In [94]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [95]:
x_reshaped.squeeze().shape

torch.Size([9])

In [102]:
# torch.unsqueeze() -- adds a single dimension to a target tensor at specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f'Previous shape: {x_squeezed.shape}')

# Add an extra dimension with unsqueeze
x_unsqueeze = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueeze}")
print(f"New shape: {x_unsqueeze.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [103]:
# torch.permute -- rearranges the dimensions of a target in a specified order
x_original = torch.rand(size=(224, 224, 3)) #[height, width, colour_channels]

# Permute th original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 -> 1, 1 -> 2, 2 -> 0

print(f"Prevoius shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Prevoius shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])
